name: diletta_challenge
description: "The Diletta challenge to flutter developer."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  connectivity_plus: ^6.0.3
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter_alice: ^1.1.1
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mocktail: ^1.0.4
  pretty_dio_logger: ^1.4.0
  toastification: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.6.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          style: normal
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700